version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: install pandoc, Make and zip
          command: |
            apt update
            apt -y install pandoc make zip
      - run:
          name: Make
          command: |
            SHORT_HASH=${CIRCLE_SHA1:0:7}
            make VERSION=$SHORT_HASH
      - store_artifacts:
          path: ./pandocker-live-templates.zip
notify:
  webhooks:
    - url: $PANDOCKER_HOOK_URL
