version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: install pandoc, Make and zip
          command: apt -y install pandoc make zip
      - run:
          name: Make
          command: make
      - store_artifacts:
          path: ./pandocker-live-templates.zip
notify:
  webhooks:
    - url: $PANDOCKER_HOOK_URL
